# Generated by Django 4.2 on 2025-01-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='demo_user',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='last_name',
            field=models.CharField(default='unknown', max_length=250),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_name',
            field=models.CharField(default='unknown', max_length=250),
        ),
    ]
