# Generated by Django 4.2.15 on 2025-01-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_useranswer_demo_user_useranswer_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Pasirinkimas', 'verbose_name_plural': 'Pasirinkimai'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Klausimas', 'verbose_name_plural': 'Klausimai'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Vartotojo atsakymas', 'verbose_name_plural': 'Vartotoju atsakymai'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_status',
            new_name='is_text_field',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='text_answer',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
